version: '3.8'

services:

  postgres:
    image: postgres:12.4-alpine
    restart: on-failure
    container_name: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  api:
    build: ./Rest-Api
    container_name: rest-api
    ports: 
      - 3000:8000
    environment:
      - DB_SERVER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    links:
      - postgres

  angular:
    build: ./Calculator
    container_name: Calculator
    ports:
      - 4200:80
    links:
      - api


volumes:
  db-data:
  